---
name: Spell Check

"on":
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typos:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # v6.0.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Check spelling with typos
        # master (latest)
        uses: crate-ci/typos@57b11c6b7e54c402ccd9cda953f1072ec4f78e33
        continue-on-error: true
        with:
          files: .
          config: .typos.toml
